// Code generated by github.com/actgardner/gogen-avro/v8. DO NOT EDIT.
/*
 * SOURCES:
 *     EventHeader.avsc
 *     RobTest.avsc
 */
package abc_xx_123

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v9/compiler"
	"github.com/actgardner/gogen-avro/v9/vm"
	"github.com/actgardner/gogen-avro/v9/vm/types"
)

type UnionNullEventHeaderTypeEnum int

const (
	UnionNullEventHeaderTypeEnumEventHeader UnionNullEventHeaderTypeEnum = 1
)

type UnionNullEventHeader struct {
	Null        *types.NullVal
	EventHeader EventHeader
	UnionType   UnionNullEventHeaderTypeEnum
}

func writeUnionNullEventHeader(r *UnionNullEventHeader, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullEventHeaderTypeEnumEventHeader:
		return writeEventHeader(r.EventHeader, w)
	}
	return fmt.Errorf("invalid value for *UnionNullEventHeader")
}

func NewUnionNullEventHeader() *UnionNullEventHeader {
	return &UnionNullEventHeader{}
}

func (r *UnionNullEventHeader) Serialize(w io.Writer) error {
	return writeUnionNullEventHeader(r, w)
}

func DeserializeUnionNullEventHeader(r io.Reader) (*UnionNullEventHeader, error) {
	t := NewUnionNullEventHeader()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullEventHeaderFromSchema(r io.Reader, schema string) (*UnionNullEventHeader, error) {
	t := NewUnionNullEventHeader()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullEventHeader) Schema() string {
	return "[\"null\",{\"doc\":\"The below fields include header information and should be included on every event in the DESP. Inspired by: https://github.com/cloudevents/spec/blob/v0.2/spec.md\",\"fields\":[{\"doc\":\"A unique identifier of the event - for example, a randomly generated GUID\",\"name\":\"id\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"}},{\"doc\":\"Time the event occurred in milliseconds since epoch, UTC timezone.\",\"name\":\"time\",\"type\":\"long\"},{\"doc\":\"Type of occurrence which has happened. Reference the domain.event registered in schema-registry.\",\"name\":\"type\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"}},{\"doc\":\"Service that produced the event. Future: reference to producer registry.\",\"name\":\"source\",\"type\":{\"avro.java.string\":\"String\",\"type\":\"string\"}}],\"name\":\"EventHeader\",\"namespace\":\"com.kroger.desp.commons.desp.healthcheck.rph\",\"type\":\"record\"}]"
}

func (_ *UnionNullEventHeader) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullEventHeader) SetLong(v int64) {

	r.UnionType = (UnionNullEventHeaderTypeEnum)(v)
}

func (r *UnionNullEventHeader) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.EventHeader = NewEventHeader()
		return &types.Record{Target: (&r.EventHeader)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullEventHeader) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullEventHeader) Finalize()                        {}

func (r *UnionNullEventHeader) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullEventHeaderTypeEnumEventHeader:
		return json.Marshal(map[string]interface{}{"com.kroger.desp.commons.desp.healthcheck.rph.EventHeader": r.EventHeader})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullEventHeader")
}

func (r *UnionNullEventHeader) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["com.kroger.desp.commons.desp.healthcheck.rph.EventHeader"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.EventHeader)
	}
	return fmt.Errorf("invalid value for *UnionNullEventHeader")
}
